// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWvuI6RvYL5NJTDs9FxILzquPo48ULTng',
    appId: '1:734985855475:web:25deec09ad301e56067286',
    messagingSenderId: '734985855475',
    projectId: 'crud-9aa98',
    authDomain: 'crud-9aa98.firebaseapp.com',
    storageBucket: 'crud-9aa98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7fU9Gpg7ecwZwe_yX640xw17Ug7PoMKc',
    appId: '1:734985855475:android:e4bb73b8531b8c10067286',
    messagingSenderId: '734985855475',
    projectId: 'crud-9aa98',
    storageBucket: 'crud-9aa98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnsWXIWmq1eFgC1632gRV3L7X7IOnRVjo',
    appId: '1:734985855475:ios:3b24d08e6e718f87067286',
    messagingSenderId: '734985855475',
    projectId: 'crud-9aa98',
    storageBucket: 'crud-9aa98.appspot.com',
    iosClientId: '734985855475-24fda0ms8toup0l3uu63ql2fg06li4sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnsWXIWmq1eFgC1632gRV3L7X7IOnRVjo',
    appId: '1:734985855475:ios:3b24d08e6e718f87067286',
    messagingSenderId: '734985855475',
    projectId: 'crud-9aa98',
    storageBucket: 'crud-9aa98.appspot.com',
    iosClientId: '734985855475-24fda0ms8toup0l3uu63ql2fg06li4sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudfire',
  );
}
